# Generated by Django 4.2.7 on 2023-12-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Specification', models.CharField(blank=True, max_length=500, null=True)),
                ('Rating', models.CharField(blank=True, max_length=100, null=True)),
                ('MRP_Price', models.IntegerField(blank=True, null=True)),
                ('Deal_Price', models.IntegerField(blank=True, null=True)),
                ('Delivery_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
