# Generated by Django 4.2.7 on 2024-01-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Category',
            new_name='Category_Name',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='Deal_Price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='productdb',
            old_name='Delivery_Status',
            new_name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='MRP_Price',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Specification',
        ),
        migrations.AddField(
            model_name='categorydb',
            name='Phone_Image',
            field=models.ImageField(blank=True, null=True, upload_to='PhoneImages'),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Product_Image1',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages'),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Product_Image2',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages'),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Product_Image3',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages'),
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='Description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
